#!/bin/bash
#
# Set up a Docker environment.
#
echo "Build Docker environment using latest base image."

docker-compose build --pull --no-cache

docker run -it --mount "type=bind,source=$(pwd)/scraper/,target=/scraper/" selenium-m1 /bin/bash -c "python3 ./scraper/scraper.py"

# to suppress creation of bycache folder:
#docker run -it --mount "type=bind,source=$(pwd)/scraper/,target=/scraper/" selenium-m1 /bin/bash -c "python3 -B ./scraper/scraper.py"